version: '3.8'

services:
  
  app:
    container_name: task_management_test
    build:
      context: .
      target: testing
    env_file:
      - src/config/env/testing.env
    command: npm run test
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_management_test
    ports:
      - '5434:5432'
