version: '3.8'

services:
  
  app:
    container_name: task_management_prod
    build:
      context: .
      target: production
    env_file:
      - src/config/env/production.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_management_prod
    ports:
      - '5435:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
