name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main
      - dev
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nestjs-task-management:${{ github.sha }}
          file: Dockerfile
          
      - name: Run tests (testing environment)
        if: github.ref == 'refs/heads/test'
        run: |
          docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit

      - name: Deploy to production (production environment)
        if: github.ref == 'refs/heads/main'
        run: |
          docker-compose -f docker-compose.prod.yml up --build
